baseURL = "https://omermertkaya.github.io/"
languageCode = "en-us"
title = "Ömer Mert Kaya"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""

[taxonomies]
  tag = "tags"

[author]
    name = "Omer Mert KAYA"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
    math = true
    # Blog description at the top of the homepage. Supports markdown.
    description = "Ömer Mert Kaya'nın Kişisel Sayfası, IAM ve Security Engineer Blog yazıları"

    showReadMore = false

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

    # Add links to your accounts. Remove the ones you don't want to include.
    # Main
    email = "omermertkaya@hotmail.com.tr"
    linkedin = "https://linkedin.com/in/omermertkaya"

    # Programming
    github = "https://github.com/omermertkaya"

    # SEO settings

    author = "Omer Mert KAYA"
    keywords = "ömer mert kaya'nın kişisel bloğu, identity and access management, kimlik ve erişim yönetimi, security blog"

# Menu links along the sidebar navigation.


[[menu.main]]
    identifier = "Anasayfa"
    name = "Anasayfa"
    url = "/"
    weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
    identifier = "about"
    name = "Hakkında"
    url = "/about/"
    weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
    identifier = "ozgecmis"
    name = "Özgeçmiş"
    url = "/ozgecmis/"
    weight = 3 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.



[[menu.main]]
    identifier = "tags"
    name = "Etiketler"
    url = "/tags/"
    weight = 4

[[menu.main]]
    name = "Arşiv"
    identifier = "archives"
    url = "/archives/"
    weight = 5

    

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true